# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\x12\x0brpc_package\"8\n\nmes2server\x12\x0c\n\x04mes1\x18\x01 \x01(\t\x12\x1c\n\x14storage_time_seconds\x18\n \x01(\x05\"8\n\nmes2client\x12\x0c\n\x04mes2\x18\x01 \x01(\t\x12\x1c\n\x14storage_time_seconds\x18\n \x01(\x05\x32K\n\x06pubsub\x12\x41\n\x0bpubsubServe\x12\x17.rpc_package.mes2server\x1a\x17.rpc_package.mes2client\"\x00\x62\x06proto3')



_MES2SERVER = DESCRIPTOR.message_types_by_name['mes2server']
_MES2CLIENT = DESCRIPTOR.message_types_by_name['mes2client']
mes2server = _reflection.GeneratedProtocolMessageType('mes2server', (_message.Message,), {
  'DESCRIPTOR' : _MES2SERVER,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.mes2server)
  })
_sym_db.RegisterMessage(mes2server)

mes2client = _reflection.GeneratedProtocolMessageType('mes2client', (_message.Message,), {
  'DESCRIPTOR' : _MES2CLIENT,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.mes2client)
  })
_sym_db.RegisterMessage(mes2client)

_PUBSUB = DESCRIPTOR.services_by_name['pubsub']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MES2SERVER._serialized_start=29
  _MES2SERVER._serialized_end=85
  _MES2CLIENT._serialized_start=87
  _MES2CLIENT._serialized_end=143
  _PUBSUB._serialized_start=145
  _PUBSUB._serialized_end=220
# @@protoc_insertion_point(module_scope)
